! PROGRAM FOR BISECTION METHOD 
F(X)=COS(X)-X*EXP(X)
WRITE(*,*)'ENTER THE VALUE OF A,B'
READ(*,*)A,B
20 X=(A+B)/2
IF(ABS(F(X)).LT.0.0001)GOTO 10
IF(F(A)*F(X).LT.0)THEN
B=X
ELSE
A=X
ENDIF
GOTO 20
10 WRITE(*,30)X
30 FORMAT(1X,'ROOT=',F6.3)
STOP
END      