! PROGRAM FOR EULERS METHOD
  REAL X0,Y0,N
  WRITE(*,*)'ENTER INITIAL VALUE X0 , Y0 '
  READ(*,*)X0,Y0
  WRITE(*,*)'ENTER THE VALUE OF H'
  READ(*,*)H
  WRITE(*,*)'ENTER THE VALUE AT WHICH RESULT TO BE FOUND'
  READ(*,*)XK
  N=(XK-X0)/H
  DO 15 I = 1,N
  AK1=CALC(X0,Y0)
  AK2=H*AK1
  X1=X0+H
  Y1=Y0+AK2
  X0=X1
  Y0=Y1
  WRITE(*,*)'THE VALUE OF X AND Y'
  WRITE(*,2)X1,Y1
 2 FORMAT(2F15.4)  
15 CONTINUE
  STOP
  END 
  FUNCTION CALC(X0,Y0)
  CALC=Y0+EXP(X0)
  RETURN 
  END

 