!PROGRAM FOR GAUSS ELIMINATION 
DIMENSION A(10,10),X(10)
WRITE(*,*)'TYPE N'
READ(*,*)N
WRITE(*,*)'THE VALUE OF COEFFICIENTS AND RHS'
DO 10 I=1,N
READ (*,*)(A(I,J),J=1,N+1)
10 CONTINUE
DO 20 K=1,N-1
DO 20 I=K+1,N
RATIO=A(I,K)/A(K,K)
DO 20 J=1,N+1
20 A(I,J)=A(I,J)-RATIO*A(K,J)
X(N)=A(N,N+1)/A(N,N)
DO 30 K=N-1,1,-1
X(K)=A(K,N+1)
DO 40 J=K+1,N
40 X(K)=X(K)-A(K,J)*x(J)
30 X(K)=X(K)/A(K,K)
DO 50 I=1,N
WRITE(*,*)X(I)
50 CONTINUE
END      