!CURVE FITTING
DIMENSION X(10),Y(10)
REAL X,Y,SUMX,SUMY,SUMXX,SUMXY,A,B
SUMX=0.0
SUMY=0.0
SUMXX=0.0
SUMXY=0.0
WRITE(*,*)'ENTER THE VALUE OF N'
READ(*,*)N
WRITE(*,*)'ENTER THE VALUE OF X AND Y'
READ(*,*)(X(I),Y(I),I=1,N)
DO I=1,N
  SUMX=SUMX+X(I)
  SUMY=SUMY+Y(I)
  SUMXX=SUMXX+X(I)*X(I)
  SUMXY=SUMXY+X(I)*Y(I)
  END DO
  DENO=(N)*SUMXX-SUMX*SUMX
  B=((N)*SUMXY-SUMX*SUMY)/DENO
  A=(SUMY-B*SUMX)/FLOAT(N)
  WRITE(*,*)'SLOPE=',B
  WRITE(*,*)'INTERCEPT=',A
  WRITE(*,*)'THE EQUATION OF THE STRAIGHT LINE IS: Y=',B,'X+',A
  STOP 
  END