! PROGRAM FOR TRAPEZOIDAL RULE 
F(X)=EXP(SIN(X))
WRITE(*,*)'THE STARTING AND ENDING POINT:'
READ(*,*)A,B
WRITE(*,*)'THE NUMBER OF INTERVALS IS:'
READ(*,*)N
H=(B-A)/FLOAT(N)
X0=A
XN=B
SUM3=0
SUM=F(X0)+F(XN)
DO 5 I=1,N-1
  XI=A+(I*H)
  SUM2=2.0*F(XI)
  SUM3=SUM3+SUM2
  5 CONTINUE
  SUM3=SUM+SUM3
  SUM=(H/2.0)*SUM3
  WRITE(*,*)'THE INTEGRAL VALUE IS:',SUM
  STOP 
  END
  